### ISSUE TITLE
Warning Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by rogerdavilabap** [mansour-ahmed/ng-animate-scroll#1]
The utility is throwing these warnings:

WARNING in ./node_modules/ng-animate-scroll/node_modules/@angular/core/fesm5/core.js
5560:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ng-animate-scroll/node_modules/@angular/core/fesm5/core.js
5572:15-102 Critical dependency: the request of a dependency is an expression

**Comment by mansour-ahmed** [comment]
This should be now fixed!
