### ISSUE TITLE
Error when building for production

### ISSUE THREAD

**Issue by thecoconutstudio** [mansour-ahmed/ng-animate-scroll#2]
running `ng build --prod` throws an error

`ERROR in ../ng-animate-scroll/animate-scroll.module.ts(3,2): Error during template compile of 'AnimateScrollModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.`

**Comment by mansour-ahmed** [comment]
now I have this fixed! closing the issue but feel free to let me know in case you are facing any other issues. Please note now the library requires angular 7 for it to work properly!
